version: '3.7'

networks:
  proxy-idp:

services:
  proxy-idp-nginx:
    container_name: proxy-idp-nginx
    image: docker.io/nginx
    networks:
      proxy-idp:
        aliases:
          - proxy-idp.labb.swefed.se
    volumes:
      - ./nginx/config/nginx/nginx.conf:/etc/nginx/nginx.d
      - ./nginx/config/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/config/cert:/etc/nginx/conf.d/cert/
    ports:
      - 443:443
    depends_on:
      - proxy-idp-satosa

  proxy-idp-pyff:
      container_name: proxy-idp-pyff
      restart: always
      build:
          context: ./
          dockerfile: pyff/Dockerfile
      networks:
        proxy-idp:
          aliases:
            - pyff.proxy-idp.labb.swefed.se
      volumes:
        - ./pyff/config/pyff/:/opt/pyff/
      ports:
        - 8081:8081


  proxy-idp-satosa:
      container_name: proxy-idp-satosa
      restart: always
      build:
          context: ./
          dockerfile: satosa/Dockerfile
      environment:
          SATOSA_CONFIG: /opt/satosa/proxy_conf.yaml
      volumes:
        - ./satosa/opt/satosa:/opt/satosa
      networks:
        proxy-idp:
          aliases:
            - satosa-int.proxy-idp.labb.swefed.se
      ports:
        - 8443:8443
      depends_on:
        - proxy-idp-pyff
